<!DOCTYPE html>
<html>
<head>
	<title>text15</title>
	<script type="text/javascript">
	//PPT 21 Error及异常处理
	var a = new Array(-5);//报错
	//异常处理语法（try,catch,finally），不能只有try
	try{
		var a = new Array(-5);
		console,log("xx");//上面的语句有错误，这条语句不执行
	}
	catch(e){
		console.log(e);
	}
	finally{
		console.log("finally");
	}

	//抛出字符串
	try{
		throw "abc";
	}
	catch(e){
		console.log(e);
	}//abc

	//try里面的代码没有错误，则不执行catch里面的代码
	try{
		console.log("xx");
	}
	catch(e){//没有捕获到异常，不执行
		console.log(e);
		console.log("yy");
	}//xx

	console.warn("yy");//警告
	console.assert(3>2,"xx");//判断括号内的表达式是否为真,如果为真，则不输出后面的内容，若为假，则报错且输出后面的内容

	//JS中异常处理嵌套的情况
	try{
		try{
			throw "oops";
		}
		catch(ex){
			console.log("inner",ex);
		}
		finally{
			console.log("finally");
		}
	}
	catch(ex){//没有接收到任何异常，不执行
		console.log("outer",ex);
	}//inner oops    finally


	try{
		try{
			throw "oops";
		}
		catch(ex){
			console.log("inner",ex);
			throw ex;//下面找不到catch，就把异常抛出外层
		}
		finally{
			console.log("finally");
		}
	}
	catch(ex){
		console.log("outer",ex);
	}//inner oops    finally    outer oops


	try{
		function abc(x,cb){
			console.log(x);
			cb();
		}
		abc("xx",function(){
			var arr = new Array(-1);
		});
	}
	catch(e){
		console.log(e);
	}//能捕获到异常

	try{
		function abc(x,cb){
			console.log(x);
			cb();
		}
	}
	catch(e){
		console.log(e);
	}
	abc("xx",function(){
			var arr = new Array(-1);
	});//捕获不到异常

	//Error对象

	//引用错误 ReferenceError
	try{
		var x = y;
	}catch(e){
		console.log(e.name,e.message);
	}

	//范围错误 RangeError
	try{
		var a = new Array(-1);
	}catch(e){
		console.log(e.name,e.message);
	}

	//类型错误 TypeError
	try{
		var a;a.aa();
	}catch(e){
		console.log(e.name,e.message);
	}
	</script>
</head>
<body>

</body>
</html>